# .streamlit/secrets.toml

[secrets]

# O ID da sua planilha do Google Sheets
GOOGLE_SHEET_ID = "1Bzu8sRNq-V1jFMc_Ow2AGtj_6TInXh9n0vRWWwlnKQQ"

# A string completa do seu arquivo JSON de credenciais
GCP_SERVICE_ACCOUNT_JSON = '''
{
  "type": "service_account",
  "project_id": "dashboardvendasstreamlit",
  "private_key_id": "76401ce9c8171aae89d3fcce3aa0656b9745f072",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC2G6qk5JzR4VEf\njIj6+T8a/GiebpAvFffyyA+Ov7ojO9IZylGr7fJade0pxdXZH/WlfMv5AJMIvPu1\nvTPZc/cGvektpXwaCyi5YsKA2B92P2/1Kg9srNARrk0vqw67qTJ7LN6sBBGPKl9z\ni3JgJyZah0XcDiIFliEKfN5ACFMlb0sU3pEzPGu2mec59jqORWZn+BQilQGusCzl\nx7ntZUkmAib8Bvi92jcS8/3qsXrtvJNuSpUYxlNOFkZR/jatCkQIw64i6rfUf8q/\nV8RcjyrC8BhhFIT0QF0IneNXxBC6iv45evNf5/5m3uKxObwWeEKCVKToVWOdpzwx\nBNt2VRqFAgMBAAECggEAGHh+RTsdIYzT8FfbnlH422D4k/WKdXFPyLV+dbGoywxC\nTsnjkKVgUCyRim/1rQAA69RpulOL7nwqnMDIY1uUYbkKSOJ4Wy2Nst+lAFhKXgLn\nQfv9Z56PNRkFcTbcu3XgfTHJ2DaRv3mzqtydqXMJUdfkmM3jX3nNhdHCsbsMpTZl\nXv7z6GnGJy/BDDxPU1QEbsy9WjlU5s8thqQM6nZZvmze0jJcDvUYioJZTuKrDzHu\n/9UGjniD0Oetj8l5k4yxV21ZykuuGjn7Tbtx0CHokkiy4hBX18pQZ93w8Jv2uXm5\nTzHVgiOWbFdtN6zzsNu4ucUBUV8k51bKY8m2LfCFcQKBgQDziUq38AKiTzFcjsJm\nmo+1drYz3TKao8jEp4hvkGvP1shWFaPt7KAMiX2ZkL5FO33RXYaS0lCNwwC/NIeV\nzeBV5vgUZ2q+0g04dhbf6BxNVy0+pZIrfSCKN7QC2bixhGgmeeb3ELU825vfC7vQ\noK/A36NgW43NP62CbUDWlIZK6QKBgQC/bZGGovmkodrsUDRoVTpMYcttn0pyFbrg\nqydV6vxJoKkZ5+hkFNdYOycRGq5cQsdSFRE0vWj8v5zcjRp/LfaVC5SnKILagP+3\nmub+bRorC5dx6vkWF9DK466uwMpoFFRxBPK3i+C/1Ll/4uGwoQqFSLOIW6OMPKRI\nrqxBeRCZPQKBgBAYE5sCPnpRd3ahbJFxR2v7k2DsDksP5dWxKKAO0EEk9YpS1cmE\nJQePEoDSgvB6VP9ACgOr6Gzl5Se9pfQtbdTfdaeLig9gPEVt8GcNpMkrqK7KLFW5\naCwaMEg78SuyD1vzlGLhdMi3zp433UqVQ+ggH2DfzAgzXBkRdUZ4/EL5AoGALFkn\nAMkbCuAQhvTh31X3ZqC1b1Ua+yk7nTcpqscA4dHdu0m11hHZ/e/eUiEbSfaSlNqa\nnNxQyVVe8t2hyNsOKGOBceR5xENketXhNAp0qIpL8LFeOZcU4Rw0aPnzKn+jPHfH\n/2vhiq+utgkK/k+gz1YTecC5OBEIgmotMBHrHYUCgYBuVtNqf1Q+VxPOUwIxYf0B\nOCOdSaY2G+N8KvBPZAY3hgFmai0lfdT1xoDcn5qLoLFe2Qk8kl5TQZbUy/mg+HPz\nf42UIrbBxMCyn6hX9Q0glqYhhJpwSdesKcthPdpVW1qrgh5ARQPRcuRMcQ/Y+bWT\nMJgIDQHBXWHXPnYg4RyD0Q==\n-----END PRIVATE KEY-----\n",
  "client_email": "streamlit-sheets-access@dashboardvendasstreamlit.iam.gserviceaccount.com",
  "client_id": "115739918191579252700",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets-access%40dashboardvendasstreamlit.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
'''
